# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - run: touch ./src/main/resources/application-secret.properties
    - run: echo "${{ secrets.APPLICATION_SECRET }}" > ./src/main/resources/application-secret.properties
    - run: cat ./src/main/resources/application-secret.properties
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        run: ./gradlew clean build
        
        ## gradle build
    - name: bootJar with Gradle
      run: ./gradlew bootJar

          # Jar 파일 Copy
    - name: Check Jar File
      run: ls ./build/libs/
    
    - name: Move to Sever Jar
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_NAME }}
        password: ${{ secrets.FTP_PWD }}
        port: ${{ secrets.FTP_PORT }}
        source: "./build/libs/*.jar"
        target: '/home/black9769/be'
        
    - name: Deploy Confirm
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_NAME }}
        password: ${{ secrets.FTP_PWD }}
        port: ${{ secrets.FTP_PORT }}
        script: |
           cd /home/black9769/be
           ls -al
           ./start.sh
